let dateTime=new Date();
console.log(dateTime)
console.log(Date.now())
console.log(dateTime.getDate())
console.log(dateTime.getDay())
console.log(dateTime.getFullYear())
console.log(dateTime.getHours())
console.log(dateTime.getMinutes())
console.log(dateTime.getSeconds())
console.log(dateTime.getTime())

console.log(dateTime.setDate(18))
console.log(dateTime.setMonth(5))
console.log(dateTime.setFullYear(2050))
console.log(dateTime.toDateString())
console.log(dateTime.toISOString())
console.log(dateTime.toJSON())
console.log(dateTime.toUTCString())