console.log(Math.abs(-45))   // change sign to positive
console.log(Math.exp(2))
console.log(Math.trunc(5.87))
console.log(Math.sqrt(36))
console.log(Math.random())
console.log(Math.round(4.3))
console.log(Math.ceil(6.1))
console.log(Math.floor(4.7))
console.log(Math.pow(2,3))
console.log(Math.max(32,65,23,6))
