let str="Hello World"
console.log(str[1])
console.log(str.charAt(6))
console.log(str.endsWith("rld"))
console.log(str.includes('r'))
console.log(str.indexOf("W"))
console.log(str.padEnd(20,'!'))
console.log(str.padStart(20,'$'))
console.log(str.repeat(4))
console.log(str.replace('World','Everyone'))
console.log(str.slice(6,8))
console.log(str.concat(" Js"))
console.log(str.substring(2,5))
console.log(str.split(","))
console.log(str.toUpperCase())
console.log(str.trim())
console.log(str.search("Wor"))